### ISSUE TITLE
Transfer stats (old stats)

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#342]
As of now, the current user stats are being stored in shared preferences which makes it vulnerable to data loss in case the app is uninstalled or the device is reset. To mitigate this risk, we need to store the user stats on the server. However, the endpoint for this is still in development and will be updated by Romain.

The following user stats need to be stored on the server:

- Mark As Listened state (right now the format is listened[sessionID])
- Longest streak
- Current streak
- Number of sessions listened
- Number of minutes listened
- Once the stats are uploaded to the server, the methods used to store these stats in local storage should be deprecated to ensure that the server remains the single source of truth for user stats.

### Tasks:

- [ ] Update the codebase to send user stats to the server endpoint.
- [ ] Collaborate with the backend team led by @scouech to integrate the endpoint to store user stats on the server.
- [ ] Handle network errors and edge cases such as server downtime and retry mechanisms.
- [ ] Update the app to fetch user stats from the server instead of local storage.
- [ ] Deprecate the methods used to store user stats in local storage.
- [ ] Ensure backward compatibility for users who have not yet updated the app.

### Acceptance Criteria:

- [ ] User stats are stored on the server.
- [x] The endpoint for storing user stats is integrated and functional by the backend team led by Romain.
- [ ] The app fetches user stats from the server instead of local storage.
- [ ] The methods used to store user stats in local storage are deprecated.
- [ ] The app gracefully handles network errors and edge cases.
- [ ] Backward compatibility is maintained.

**Comment by scouech** [comment]
@osamaasifoak so what we would do is that the endpoint will be able to accept JSON. 
The JSON should contain all the data that Mike mentioned. 

It would be great if you could share an example of all the data combined as JSON here, so that I can then see how to handle it on the server side. 

Is there something you could start with @osamaasifoak ?
Cheers

**Comment by osamaasifoak** [comment]
Here you go @scouech 
`{
  "userId": 1,
  "currentStreak": 1,
  "minutesListened": 17,
  "listendedSessionsNum": 3,
  "longestStreak": 1,
  "listenedSessionIds": [
    2,
    9
  ]
}`

**Comment by michaelcspeed** [comment]
Looks good to me thanks @osamaasifoak

**Comment by scouech** [comment]
@osamaasifoak the endpoint is ready.
We are using the `POST /events` endpoint with the event `name = transferStats`

Here is the payload format:

```
{
    "name": "transferStats",
    "payload": {
        "currentStreak": 18,
        "minutesListened": 70,
        "listendedSessionsNum": 763,
        "longestStreak": 17,
        "listenedSessionIds": [ 2, 9, 20, 9, 2, 87 ]
    }
}
```

As discussed, this specific call should be made after the `POST /users` call is made (to get a token if it's the first time opening the app) and before `GET /home`, `GET /stats` and `POST /events: appOpened` are made.

The staging env will post the event payload to Slack if it worked or not. 

The documentation is on Postman:
[https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-b4817711-2c0b-49e1-966f-7591dbeca6de?ctx=documentation](https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-b4817711-2c0b-49e1-966f-7591dbeca6de?ctx=documentation
)

**Comment by osamaasifoak** [comment]
16 ~ 20 hrs

**Comment by scouech** [comment]
Seems to work. Will get it tested by the rest of the team once we have the the beta on the play store (otherwise cant test on android)
