### ISSUE TITLE
Add user authentication flow

### ISSUE THREAD

**Issue by osamaasifoak** [meditohq/medito-app#346]
For maintaining user stats. We added a new flow of user account creation. Through, this we can keep track of the user-listened sessions,  their streaks and hours listened, etc. The flow is pretty simple for creating an account they only need to provide an email to receive an OTP and after verifying an OTP they are good to use the app. **Note:** This account creation option is not mandatory means they can still use the app without creating an account but their data will be lost if they uninstalled the app or changed the device. 

Here's the **Figma** link:
[Authentication flow](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?node-id=938-5718&t=oqOBSmblLfb6cQie-0)

### Tasks:

- [x] Create a UI according to the Figma design.
- [x] Collaborate with the backend team led by @scouech to integrate the endpoint.
- [x] Handle network errors and edge cases such as server downtime and retry mechanisms.
- [x] Handle miscellaneous cases if occur.
- [ ] Write unit tests

### Acceptance Criteria:

- [x] User authentication UI according to the provided design.
- [x] Implemented the endpoint provided by the backed team.
- [x] Successful account creation.
- [x] Handled network errors, etc.
- [ ] Write test cases

**Comment by scouech** [comment]
This is great @osamaasifoak , thank you so much!
